permissions: write-all

name: Build and Upload Website Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Assuming the build process creates the final files in a 'dist' directory
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: src/
