permissions: write-all

name: Build, Push Docker Image, and Deploy with Pre-Deployment Security Scan and tfsec Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:

      - name: Run Trivy on Repo
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: . 
            file: ./Dockerfile
            push: true
            tags: mohd1995/testing:latest
      
          
  