permissions: write-all

name: Build, Push Docker Image, and Deploy with Pre-Deployment Security Scan and tfsec Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: . 
            file: ./Dockerfile
            push: true
            tags: mohd1995/testing:latest
          
  deploy-infrastructure:
    needs: build-and-push-docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Latest Docker Image
        run: docker pull mohd1995/testing:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2   

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure
    
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure
      
      -  name: Terraform Destroy
         run: terraform destroy -auto-approve
         working-directory: ./infrastructure