name: CI/CD Pipeline with Docker, Codacy, and Terraform

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mohd1995/webhosting:latest .
          docker push  mohd1995/webhosting


      - name: Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          gh-code-scanning-compat: true
        # Assuming the output can be redirected or saved, update this part accordingly
        # It may require custom scripting if the action doesn't support log output directly

      # New step to upload the analysis logs to S3
      - name: Upload Codacy logs to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Assuming logs are saved to a file named codacy-analysis.log
          # Update the file path and bucket name as necessary
          aws s3 cp codacy-analysis.log s3://codacy-result/path/to/logs/codacy-analysis-$(date +%Y-%m-%d-%H-%M-%S).log

  terraform-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infrastructure/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Wait 3 minutes
        uses: actions/wait-for-check@v2
        with:
          timeoutSeconds: 180 # Waits for 3 minutes

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./infrastructure/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
