permissions: write-all

name: 'Build and Deploy with Pre-Deployment Security Scan'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    name: 'Build, Security Scan, and Deploy Terraform Infrastructure'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Run Trivy vulnerability scanner on filesystem and save output
        run: |
          trivy filesystem --format json . > trivy-results.json
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload Trivy scan results to S3
        run: |
          aws s3 cp trivy-results.json s3://your-s3-bucket-name/trivy-results-${{ github.run_id }}.json
