permissions: write-all

name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tfsec_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install AWS CLI
      run: pip install awscli

    - name: Run tfsec and save results
      run: tfsec . --format=default --soft-fail > tfsec_results.txt

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload tfsec results to S3
      run: aws s3 cp tfsec_results.txt s3://git-mo-aws/tfsec/tfsec_results.txt
