permissions: write-all

name: Trivy Container Image Scan

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  fs-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yml
          ignore-unfixed: true
          format: 'table'
          severity: 'LOW'
          exit-code: 0

  container_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: mohd1995/testing:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mohd1995/testing:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os, library'
          severity: 'CRITICAL,HIGH'
          trivy-config: trivy.yml

  deploy-infrastructure:
    needs: container_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Pull Latest Docker Image
        run: docker pull mohd1995/testing:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2   

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure
    
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infrastructure
    
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ./infrastructure


      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure
      
      -  name: Terraform Destroy
         run: terraform destroy -auto-approve
         working-directory: ./infrastructure




  